apiVersion: v1
kind: ConfigMap
metadata:
  name: sabnzbd-gluetun-config
  namespace: media
data:
  VPN_SERVICE_PROVIDER: windscribe
  VPN_TYPE: wireguard
  WIREGUARD_IMPLEMENTATION: userspace
  TZ: Australia/Brisbane
  HTTP_CONTROL_SERVER_ADDRESS: ":8000"
  HEALTH_SERVER_ADDRESS: ":9999"
  FIREWALL_INPUT_PORTS: "8080,8000,9999"
  FIREWALL_OUTBOUND_SUBNETS: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
