apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-gluetun-windscribe
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: sabnzbd-gluetun-windscribe
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: vpn/gluetun/windscribe
        property: wireguard_private_key
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: vpn/gluetun/windscribe
        property: wireguard_addresses
    - secretKey: WIREGUARD_PRESHARED_KEY
      remoteRef:
        key: vpn/gluetun/windscribe
        property: wireguard_preshared_key
