apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-news-server
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: sabnzbd-news-server
    creationPolicy: Owner
  data:
    - secretKey: SABNZBD_NEWS_SERVER
      remoteRef:
        key: media/sabnzbd/news-server
        property: server
    - secretKey: SABNZBD_NEWS_USERNAME
      remoteRef:
        key: media/sabnzbd/news-server
        property: username
    - secretKey: SABNZBD_NEWS_PASSWORD
      remoteRef:
        key: media/sabnzbd/news-server
        property: password
