apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - externalsecret-news-server.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

labels:
  - includeSelectors: true
    pairs:
      app: sabnzbd
